#os: osx

# language
language: python

# command to install dependencies
install:
  - pip install -r requirements.txt

# database
addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database games_minesweeper;' -U postgres

# command to run tests
script: python manage.py test
