# Generated by Django 3.1.4 on 2021-01-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='cell',
            name='label',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
