# Generated by Django 3.1.4 on 2021-01-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0006_auto_20210124_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
