# Generated by Django 3.1.4 on 2021-01-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0007_cell_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='nr_hidden',
            field=models.IntegerField(default=0),
        ),
    ]
