# Generated by Django 3.1.4 on 2021-02-01 21:01

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0010_auto_20210130_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='state_sm',
            field=django_fsm.FSMIntegerField(choices=[(0, 'created'), (1, 'started'), (2, 'ended'), (3, 'paused')], default=0, protected=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='state',
            field=models.CharField(blank=True, choices=[('init', 'Init'), ('start', 'Start'), ('pause', 'Pause'), ('end', 'End')], max_length=16, null=True),
        ),
    ]
