# Generated by Django 3.1.4 on 2021-02-02 01:29

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0011_auto_20210201_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='state',
        ),
        migrations.AlterField(
            model_name='board',
            name='state_sm',
            field=django_fsm.FSMIntegerField(choices=[(0, 'created'), (1, 'started'), (3, 'ended'), (2, 'paused')], default=0, protected=True),
        ),
    ]
