# Generated by Django 3.1.4 on 2021-02-18 19:02

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0014_auto_20210205_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='state_sm',
            field=django_fsm.FSMIntegerField(choices=[(0, 'init'), (1, 'start'), (2, 'pause'), (3, 'end win'), (4, 'end lose')], default=0),
        ),
    ]
