# Generated by Django 3.1.4 on 2021-01-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('value', models.IntegerField()),
                ('hidden', models.BooleanField()),
                ('mined', models.BooleanField()),
                ('flagged', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('mines', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('nr_hidden_cells', models.IntegerField()),
                ('state', models.CharField(max_length=16)),
                ('cells', models.ManyToManyField(blank=True, to='minesweeper.Cell')),
            ],
        ),
    ]
