# Generated by Django 3.1.4 on 2021-01-21 21:51

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('rows', models.IntegerField(default=1)),
                ('cols', models.IntegerField(default=1)),
                ('mines', models.IntegerField(default=1)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('state', models.CharField(choices=[('BEGIN', 'Begin'), ('IN_PROGRESS', 'In progress'), ('PAUSE', 'Pause'), ('END', 'End')], default='BEGIN', max_length=16)),
                ('numbers', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('apparent', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('value', models.IntegerField()),
                ('visible', models.BooleanField(default=False)),
                ('mined', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minesweeper.board')),
            ],
        ),
    ]
