# Generated by Django 3.1.4 on 2021-01-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='duration',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
    ]
