# Generated by Django 3.1.4 on 2021-01-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0002_auto_20210113_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cols',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='duration',
            field=models.DurationField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='mines',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='nr_hidden_cells',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='rows',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='board',
            name='state',
            field=models.CharField(choices=[('BEGIN', 'Begin'), ('IN_PROGRESS', 'In progress'), ('PAUSE', 'Pause'), ('END', 'End')], default='BEGIN', max_length=16),
        ),
    ]
