# Generated by Django 3.1.4 on 2021-01-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0003_auto_20210113_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-start',)},
        ),
        migrations.AlterField(
            model_name='board',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
