# Generated by Django 3.1.4 on 2021-01-14 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0004_auto_20210113_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cells',
            field=models.ManyToManyField(null=True, to='minesweeper.Cell'),
        ),
        migrations.AlterField(
            model_name='board',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
