# Generated by Django 3.1.4 on 2021-01-14 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0005_auto_20210113_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='board',
            name='cells',
        ),
        migrations.AddField(
            model_name='cell',
            name='board',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='minesweeper.board'),
            preserve_default=False,
        ),
    ]
