# Generated by Django 3.1.4 on 2021-01-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0006_auto_20210114_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='hidden',
            new_name='visible',
        ),
    ]
