# Generated by Django 3.1.4 on 2021-01-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0007_auto_20210118_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cell',
            name='mined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cell',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cell',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
