# Generated by Django 3.1.4 on 2021-01-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0008_auto_20210118_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='value',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
