# Generated by Django 3.1.4 on 2021-01-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0009_auto_20210126_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='success',
            new_name='game_win',
        ),
        migrations.AlterField(
            model_name='board',
            name='state',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('start', 'Start'), ('pause', 'Pause'), ('end', 'End')], max_length=16, null=True),
        ),
    ]
