# Generated by Django 3.1.4 on 2021-02-06 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minesweeper', '0012_auto_20210201_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='state_sm',
            field=django_fsm.FSMIntegerField(choices=[(0, 'created'), (1, 'started'), (2, 'paused'), (3, 'end win'), (4, 'end loose')], default=0, protected=True),
        ),
    ]
