# Generated by Django 3.1.4 on 2021-02-06 03:16

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0013_auto_20210205_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='state_sm',
            field=django_fsm.FSMIntegerField(choices=[(0, 'created'), (1, 'started'), (2, 'paused'), (3, 'end win'), (4, 'end loose')], default=0),
        ),
    ]
